### ISSUE TITLE
Explicit net type deceleration needed in axilrd2wbsp.v

### ISSUE THREAD

**Issue by bchetwynd** [ZipCPU/wb2axip#10]
** Warning: ../hdl_cores/wb2axip/rtl/axilrd2wbsp.v(83): (vopt-2892) Net type of 'i_wb_data' must be explicitly declared.

**Comment by ZipCPU** [comment]
Fixed in [7e688ea](https://github.com/ZipCPU/wb2axip/commit/7e688ea8e5dca804f0414fc701a0ab7dc37cdb01)
