### ISSUE TITLE
axi2axilite.v: M_AXI_BVALID does not propagate to S_AXI_BVALID

### ISSUE THREAD

**Issue by bchetwynd** [ZipCPU/wb2axip#11]
Performing a AXI4 to WB conversion using the recommended components (per the repo's README.md)

Issued a single write, which successfully propagated to the WB target.  The axlite2wbsp component successfully generates the the assertion of M_AXI_BVALID, but I never see S_AXI_BVALID asserted.

Waveforms attached.  Parameters set to default with the exception of LGFIFO = 1

![axi2axilite_1](https://user-images.githubusercontent.com/20117197/59291541-27381980-8c49-11e9-8a39-96b30b0b597f.jpg)
![axi2axilite_2](https://user-images.githubusercontent.com/20117197/59291542-27381980-8c49-11e9-9d39-3bd93366d28e.jpg)

**Comment by bchetwynd** [comment]
Initial user error: S_AXI_AWLEN and S_AXI_AWSIZE were set incorrectly (255 and 7).  Still debugging.

**Comment by ZipCPU** [comment]
I just got to that point.  ;)

Keep going!  I've enjoyed your feedback so far.

**Comment by bchetwynd** [comment]
Thank you.

It seems as if all the conditions to generate s_axi_bvalid seem be one cycle off.  I observe that the conditions controlling the increment and decrement of bcounts are occurring on the same cycle.  

Is my WB peripheral responding too quickly?


![axi2axilite_2](https://user-images.githubusercontent.com/20117197/59294668-f90a0800-8c4f-11e9-8503-6ffc7cb9c151.jpg)
![axi2axilite_1](https://user-images.githubusercontent.com/20117197/59294669-f9a29e80-8c4f-11e9-94bd-d8989f7c2d3f.jpg)

**Comment by bchetwynd** [comment]
I should note that all my transfers are one word in size..... and thus the first and only data sent over S_AXI_WDATA has S_AXI_WLAST asserted.

**Comment by bchetwynd** [comment]
The bcounts logic (axi2axilite.v, lines 320-328) does not handle simultaneous assertions of read_from_wrfifo and (skidm_bvalid and skidm_bready).  As a result, bcounts will just continue to increment and never decrement.

**Comment by bchetwynd** [comment]
Also suggest updating axi2axilite.v, line 344 to the following:
				||((bcounts == 0) && (!wfifo_empty) && (wfifo_bcount == 1));
from:
				||((bcounts == 0) && (!wfifo_empty) && (wfifo_bcount == 0));

**Comment by ZipCPU** [comment]
I'm not sure I follow your comment about lines 320-328 not  handling simultaneous read_from_wrfifo and (skidm_bvalid & skidm_bready).  read_from_wrfifo = some_expression & (skidm_bvalid & skidm_bready), so it must always handle skidm_bvalid && skidm_bready.  See for example [line 308](https://github.com/ZipCPU/wb2axip/blob/8ae43172c2f3640105e9ce5fc9beb39c3f17837c/rtl/axi2axilite.v#L308).  As for `skidm_bready`, that will only ever be true of the outgoing `S_AXI_B*` channel isn't stalled, see for example [line 375](https://github.com/ZipCPU/wb2axip/blob/8ae43172c2f3640105e9ce5fc9beb39c3f17837c/rtl/axi2axilite.v#L375).

Dan

**Comment by ZipCPU** [comment]
As for your off by one error and your comment about bcounts checking for one rather than zero, the length field used by AXI is off by one.  Therefore, when you set AWVALID and AWLEN==1, you are asking for a burst of length two--not a burst of length one.  It is then an error to immediately set WVALID and WLAST.  That will force the return to wait an additional cycle before setting BVALID.

You'll want to set AWLEN to zero if you only want single value bursts.

Dan

**Comment by bchetwynd** [comment]
Thank you.  Things behave as expected when I pass correct parameters aw_len = 0; aw_size = 4.
