### ISSUE TITLE
High throughput AXI full master.

### ISSUE THREAD

**Issue by d953i** [ZipCPU/wb2axip#16]
Not really an issue, just wondering if you already working/planning to make one and formally verify it so I won't duplicate the work.
Looking for high throughput AXI master with simple user interface similar to used in demofull.v
Thanks!

**Comment by ZipCPU** [comment]
There are already several high throughput masters within this repository.  There's the [AXI-lite to AXI bridge](rtl/axilite2axi.v), the [WB to AXI bridge](rtl/wbm2axip.v), the [AXI crossbar](rtl/axixbar.v) and it's [AXI-lite sister](rtl/axilxbar.v), the [AXI stream to AXI (mm) bridge](rtl/axis2mm.v), and then again the [AXI (mm) to AXI stream bridge](aximm2s.v).  All of these cores are fully formally verified.  The properties necessary to verify them are available to my Patreon sponsors on request.

What more would you be looking for?
