### ISSUE TITLE
Wrong AXI-Stream port names in aximm2s.v

### ISSUE THREAD

**Issue by rlee287** [ZipCPU/wb2axip#21]
The AXI-Stream interface of the MM2S core is a master interface, so the signal prefixes should be `M_AXIS` instead of `S_AXIS`.

**Comment by ZipCPU** [comment]
Thank you!

Fixed in [a5b9c97](https://github.com/ZipCPU/wb2axip/commit/a5b9c9745a8407a8fe1f7207299e3f4802c67489)
