### ISSUE TITLE
Missing doc file lgpl-3.0.pdf?

### ISSUE THREAD

**Issue by tcmichals** [ZipCPU/wb2axip#22]
The makefile in doc, is looking for lgpl-3.0.pdf.  Is this file missing?  Also, src/lgpl-3.0.tex?

**Comment by ZipCPU** [comment]
The repository was originally licensed under LGPL.  It has since been relicensed under Apache 2.  All references to LGPL should have been removed.  I have now removed that reference from doc/Makefile.  Let me know if you find other references, and I'll adjust them.

**Comment by tcmichals** [comment]
missing src/spec.tex
