### ISSUE TITLE
axi2axilite missing DW on axi_addr instances

### ISSUE THREAD

**Issue by saberhawk** [ZipCPU/wb2axip#24]
The axi2axilite module is missing DW on both axi_addr instances which can cause incorrect addressing when C_AXI_DATA_WIDTH is set to 64

https://github.com/ZipCPU/wb2axip/blob/3d7374e538a634a5fc3be40d50e0c832f801a396/rtl/axi2axilite.v#L283

**Comment by ZipCPU** [comment]
Thanks!

Fixed in [76a1c3f](https://github.com/ZipCPU/wb2axip/commit/76a1c3fb6fbb0212870bcc58a6c0fb49942e99fd).

Dan
