### ISSUE TITLE
aximwr2wbsp increments address too early, first data written to the next incremented address

### ISSUE THREAD

**Issue by motylewski** [ZipCPU/wb2axip#25]
Simulated using Vivado 2019.2 AXI Verification IP 1.1
Data is always landing in incremented address. Both in HW and in the simulation.

In the test mit HW single  write there is the same problem - writing to addr+1 instead of addr.
![aximwr2wbsp-bug4](https://user-images.githubusercontent.com/36234891/89797759-9c43ff00-db2b-11ea-8273-1346aa124f2b.png)

**Comment by ZipCPU** [comment]
I think I see it.

Check [this patch](https://github.com/ZipCPU/wb2axip/commit/2b7af47e14c73277191f05611c205357d4a9a483), and see if it fixes your issue.

Dan

**Comment by motylewski** [comment]
Simulation looks OK now, thanks !
In HW also OK now.
But there is (and always was) another issue: endianess is swapped when writing. Reading is OK.

![aximwr2wbsp-fixed](https://user-images.githubusercontent.com/36234891/89812008-c43d5d80-db3f-11ea-9d8f-45ab80215d9e.png)

**Comment by ZipCPU** [comment]
Fixed in [864d554](https://github.com/ZipCPU/wb2axip/commit/864d554399419614a37286855a38fa538ca5411c).

Dan

**Comment by motylewski** [comment]
OK, thanks.
As for OPT_SWAP_ENDIANNESS I have added that into axim2wbsp so it is adjustable in the same way for both WR and RD channels. I am using 0 there anyway.
