### ISSUE TITLE
Syntax error in axidma.v

### ISSUE THREAD

**Issue by jiegec** [ZipCPU/wb2axip#30]
https://github.com/ZipCPU/wb2axip/blob/29fcc0b966f71fe3667a4fdfb939859aab059ae5/rtl/axidma.v#L1977-L1983

**Comment by ZipCPU** [comment]
[See this comment within the design.](https://github.com/ZipCPU/wb2axip/blob/master/rtl/axidma.v#L1484-L1492)

Dan
