### ISSUE TITLE
`s2mm` doesn't update address or len external registers

### ISSUE THREAD

**Issue by archshift** [ZipCPU/wb2axip#35]
The documentation states that `CMD_LEN` and `CMD_ADDR` should reflect the current state of the module when it is `busy`. Currently, these registers stay fixed as the user-set values.

**Comment by ZipCPU** [comment]
Please evaluate [this pull request](https://github.com/ZipCPU/wb2axip/pull/36) and see if it resolves your issue.

Thanks!

Dan

**Comment by archshift** [comment]
It looks like this exactly addresses it. Thanks Dan!
