### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by hughperkins** [ZipCPU/wb2axip#49]
Hi, looking forward to trying some of your formal verification tests against my own work. From your README, looks like the license is Apache 2.0. However, no LICENSE file currently exists in your repo, and github doesn't detect the license of your work. Dont suppose... please could you consider adding a LICENSE file to your repo? github will then pick this up, and automatically show the license type on the right hand side of your github page. (e.g. https://github.com/apache/httpd, see screenshot:

<img width="338" alt="Screen Shot 2022-05-12 at 6 26 18 AM" src="https://user-images.githubusercontent.com/123560/168050413-2ca2e1bc-d278-4134-ae4b-3882e1797b0d.png">

**Comment by ZipCPU** [comment]
I'm not convinced this needs a fix.  Every file in the repository should already be properly marked with the license it is released under.

**Comment by hughperkins** [comment]
From a legal point of view, it doesnt need to be fixed. However, from a usability point of view, I feel it is very convenient to be able to instantly see the license of a repo at a glance, without needing to dig through the readme etc.
