### ISSUE TITLE
Whether the situation crossing 4K boundary has been handled in AXIDMA？

### ISSUE THREAD

**Issue by zhoulikeda** [ZipCPU/wb2axip#51]
if source (or destination) address+ length  crossing 4K boundary, whether the situation has been handled in axidma.v to avoid crossing 4K boundary in a single axi transfer?

**Comment by ZipCPU** [comment]
The AXIDMA has been designed so that it will not cross 4kB boundaries during any transaction.  This is required by the AXI protocol, and the AXIDMA is fully compliant.

**Comment by ZipCPU** [comment]
Hmm, that doesn't read right.  The AXIDMA can be configured to move larger than 4kB, but it will not cross 4kB boundaries in any given _burst_.  ("Transaction" was really the wrong word choice.)
