### ISSUE TITLE
the patreon support

### ISSUE THREAD

**Issue by xlxwzybds** [ZipCPU/wb2axip#57]
Hi sir，
I found in the github issues that getting a formal property file like faxi_valaddr.v requires becoming a patreon member of zipcpu.

Since I am not familiar with the specific functions of using patreon, I would like to ask, if I want to learn related file content, do I only need to become a patreon member of zipcpu. I did not use a Google account to apply for github, so I was little confused about the follow-up process.

**Comment by ZipCPU** [comment]
You can find out details of becoming [a Patreon sponsor here](https://www.patreon.com/ZipCPU).  You'll find this link on every one of my blog articles.  I'm sure Patreon will want a credit card, or some other means of paying a monthly subscription.

Dan
