### ISSUE TITLE
compilation error in axi2axilite.v

### ISSUE THREAD

**Issue by bchetwynd** [ZipCPU/wb2axip#9]
Compiled with QuestSim-64-10.6c

# ** Error: ../hdl_cores/wb2axip/rtl/axi2axilite.v(443): (vlog-2110) Illegal reference to net "wfifo_empty".
# ** Error: ../hdl_cores/wb2axip/rtl/axi2axilite.v(444): (vlog-2110) Illegal reference to net "wfifo_full".
# ** Error: ../hdl_cores/wb2axip/rtl/axi2axilite.v(445): (vlog-2110) Illegal reference to net "wfifo_count".
# ** Error: ../hdl_cores/wb2axip/rtl/axi2axilite.v(447): (vlog-2110) Illegal reference to net "read_from_wrfifo".
# ** Error: ../hdl_cores/wb2axip/rtl/axi2axilite.v(624): (vlog-2110) Illegal reference to net "rfifo_empty".
# ** Error: ../hdl_cores/wb2axip/rtl/axi2axilite.v(625): (vlog-2110) Illegal reference to net "rfifo_full".
# ** Error: ../hdl_cores/wb2axip/rtl/axi2axilite.v(626): (vlog-2110) Illegal reference to net "rfifo_count".

**Comment by ZipCPU** [comment]
Fixed in [8ae4431](https://github.com/ZipCPU/wb2axip/commit/8ae43172c2f3640105e9ce5fc9beb39c3f17837c)
